{{- $apps := .Values.web -}}
{{- range $key, $app := $apps.list }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{$.Release.Name}}-{{$app.name}}-ingress"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: "{{$.Values.basePath}}/{{$app.path}}"
spec:
  rules:
  - host: hel.westeurope.cloudapp.azure.com
    http:
      paths:
      - path: {{$.Values.basePath}}/{{$app.path}}
        backend:
          serviceName: "{{$.Release.Name}}-{{$app.name}}"
          servicePort: 80
---
{{- end -}}