apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: dnatrack-web-admin
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-admin
  template:
    metadata:
      labels:
        app: web-admin
        tier: web
        tag: "v1"
    spec:
      containers:
        - name: web-admin
          image: "arukim/dnatrack-web-admin:v1"
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          - name: https
            containerPort: 443
            protocol: TCP
          volumeMounts:
          - name: app-config
            mountPath: /etc/config
      volumes:
        - name: app-config
          configMap:
            name: app